# kangeldungeon Configuration
# 大部分设置需要重启以应用更改
# MOST SETTINGS REQUIRED RESTART TO APPLY CHANGES
# 大部分设置需要重启以应用更改
# MOST SETTINGS REQUIRED RESTART TO APPLY CHANGES
# 大部分设置需要重启以应用更改
# MOST SETTINGS REQUIRED RESTART TO APPLY CHANGES

# 调试模式 debug
# Debug mode
debug: false

# 语言 language
lang: en_US



database:
  enable: false  # true: MySQL; false: SQLite
  filename: data # data.db for SQLite Database File.
  host: localhost
  port: 3306
  user: x_angelkawaii_x
  password: angelkawaii2
  database: kangeldungeon
  table: kangeldungeon_data
